<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard20</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Authors>Simon Jefferies</Authors>
		<Company>Simon Jefferies</Company>
		<Description>This package contains a set of utility classes.</Description>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<LangVersion>latest</LangVersion>
		<RootNamespace>MvvmToolkit</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
		<PackageReference Include="MinVer" Version="7.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="MissingAttributes" Version="1.1.0" />
	</ItemGroup>

</Project>
